spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5433/Client?currentSchema=client}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:2710}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          globally_quoted_identifiers: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  application:
    name: ClientService

server:
  port: ${CLIENT_SERVICE_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:${EUREKA_SERVER_PORT:8761}/eureka/

jwt:
  secret:
    access: 480d93c2e07d90fa9ad3d5d612635b2966606053e30948ddfe9ed4d3d6891514
    refresh: ZP0ffRrzcOVMlQVRrSU1uFomu4bZkymycSLRjZ4dHLnCuWA1pU/0to9rh+Q78rYc
